---
name: PR opened

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/welcome-message.yml@31e83cf3419b7230171cea9cd2e97f83bc04488f # 1.3.25
    secrets: inherit
